FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Set Python and install dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3.10 python3-pip && \
    ln -s /usr/bin/python3.10 /usr/bin/python && \
    pip install --upgrade pip

# Copy requirements and install
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements_GPU.txt

# Copy source code
COPY . .


